<Project Sdk="Microsoft.NET.Sdk.Web">

    <ItemGroup>
        <ProjectReference Include="..\WarehouseManager.Api\WarehouseManager.Api.csproj"/>
        <ProjectReference Include="..\WarehouseManager.Infrastructure\WarehouseManager.Infrastructure.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0"/>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.4"/>
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <AssemblyName>WarehouseManager.Host</AssemblyName>
        <RootNamespace>WarehouseManager.Host</RootNamespace>
    </PropertyGroup>

</Project>
